### ISSUE TITLE
GET voltage doesn't work with LINSEG

### ISSUE THREAD

**Issue by skostogl** [SixTrack/SixTrack#1072] opened 2020-11-13 12:05 UTC
Although the voltage in a crab cavity is non-zero in fort.2:
acfgah.4ar1.b1    23   3.445787875509007
GET voltage and then assigning to LINSEG doesn't seem to work:

In fort.3:
DYNK
DEBUG
DYNKSETS
FUN crabVolt1 GET acfgah.4ar1.b1 voltage
FUN ramp_CC0 LINSEG 0 10000 0 crabVolt1
SET acfgah.4ar1.b1 voltage ramp_CC0 1 10000 -1

Output:
DYNK> DEBUG Applying set #    1 on 'acfgah.4ar1.b1':'voltage', shiftedTurn =     7867, value =  0.000000000E+00
DYNK> DEBUG setvalue Element_name = 'acfgah.4ar1.b1', att_name = 'voltage', newValue =  0.000000000E+00
DYNK> DEBUG In getValue, element_name = 'acfgah.4ar1.b1', att_name = 'voltage'
DYNK> DEBUG getValue, returning =  0.000000000E+00
DYNK> DEBUG Read back value =  0.000000000E+00
DYNK> DEBUG In getValue, element_name = 'acfgah.4ar1.b1', att_name = 'voltage'
DYNK> DEBUG getValue, returning =  0.000000000E+00
DYNK> DEBUG In apply at turn 7869

**Comment by kyrsjo** [comment] 2021-09-16 12:35
Hi, I just saw this one. As specified in the manual, LINSEG expects 4 real values, not a function-name (like the 1- and 2-operand operators).

Closing this as not a bug.

**Closed by kyrsjo** 2021-09-16 12:35 UTC

**Comment by kyrsjo** [comment] 2021-09-16 12:36
What you can do, is to make a LINSEG from 0 to 1, and then multiply that function output with the GET function output.
