### ISSUE TITLE
Put the manual on the web in a better way

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#227] opened 2017-02-24 17:33 UTC
Write a readme for how to put things on http://sixtrack.web.cern.ch/SixTrack/ and delete the PDFs from the repository.

**Comment by rdemaria** [comment] 2017-05-04 07:58
Where do you want the readme?

**Comment by kyrsjo** [comment] 2017-05-04 09:44
Which readme?

**Comment by vkbo** [comment] 2018-05-18 12:50
Not sure what the issue is, but there is a new website with HTML and PDF manuals. I'm closing this.

**Closed by vkbo** 2018-05-18 12:50 UTC
