### ISSUE TITLE
Check coupling in BB lens

### ISSUE THREAD

**Issue by rdemaria** [SixTrack/SixTrack#267] opened 2017-05-10 10:17 UTC
Coupling angle might be computed incorrectly (@giadarol). @giadarol proposes to compute the divergence of a beam-beam kick with the following matrix:

{'Sig_11_0': 2.1046670129999999e-05,
 'Sig_12_0': 2.7725426699999999e-07,
 'Sig_13_0': 5.9207071659999999e-06,
 'Sig_14_0': 1.2224001670000001e-07,
 'Sig_22_0': 3.6622825020000002e-09,
 'Sig_23_0': 7.4141336339999994e-08,
 'Sig_24_0': 1.495491124e-09,
 'Sig_33_0': 3.165637487e-06,
 'Sig_34_0': 7.9058234540000002e-08,
 'Sig_44_0': 2.040387648e-09}

**Comment by rdemaria** [comment] 2017-05-16 17:09
Yes!

**Comment by kyrsjo** [comment] 2017-05-17 16:10
Working on it in https://github.com/kyrsjo/SixTrack/tree/beam-tests

**Comment by kyrsjo** [comment] 2017-05-29 15:25
Hm, is the position of the particles in x/y supposed to change in the beam lens? Some numerical inaccuracy related to the boost maybe? Because if I give a "rectangular grid" of x/y values in, after the bb kick it is distorted... I'll make a plot.

**Comment by giadarol** [comment] 2017-05-29 15:59
Hi Kyrre,
yes, the positions are supposed to change, it’s a feature of the 6D treatment. Indeed it is not really correct to call it a lens.

On 29 May 2017, at 17:25, Kyrre Ness Sjøbæk <notifications@github.com<mailto:notifications@github.com>> wrote:


Hm, is the position of the particles in x/y supposed to change in the beam lens? Some numerical inaccuracy related to the boost maybe? Because if I give a "rectangular grid" of x/y values in, after the bb kick it is distorted... I'll make a plot.

**Comment by kyrsjo** [comment] 2017-05-29 16:12
OK, thanks. I should probably read more up on how this element works...

Anyway, here is the plot for how the positions shift when going through the bb "kick":
![shift](https://cloud.githubusercontent.com/assets/1011920/26556298/08555134-449a-11e7-8624-af2023b42091.png)
Maximum value is 2.21537537852e-06 mm so pretty small.

**Comment by rdemaria** [comment] 2017-05-29 19:23
Do you have plot of the divergence of Delta px, py?

**Comment by kyrsjo** [comment] 2017-05-30 16:41
With the current status of the branch:
![figure_1](https://cloud.githubusercontent.com/assets/1011920/26594168/eae38eea-4566-11e7-9b78-e7dcea479ef9.png)
The quiver is the kick as a function of the initial position, contours the reconstructed charge density (arbitrary units).

This looks like negative covariance to me, which is not what we put in...

**Comment by kyrsjo** [comment] 2017-05-30 16:49
With the fixed coupling, as seen in this branch (which is just Riccardo's fix_beambeam_coupling merged on top of my test tools branch):
https://github.com/kyrsjo/SixTrack/tree/tests_coupling

![figure_1-1](https://cloud.githubusercontent.com/assets/1011920/26594625/a27e94c2-4568-11e7-833a-367a184d9fa2.png)

![figure_3](https://cloud.githubusercontent.com/assets/1011920/26594630/a65e9e2a-4568-11e7-8fc1-70ae05e2099f.png)

Note that the previous displacement plot was with coupling OFF (using the ibbc flag).

**Comment by rdemaria** [comment] 2017-05-30 22:46
This is what @giadarol expected for the kick. We assume that the strong bunch is described in the frame of the weak bunch. Just for the sake of being paranoid, can you do put the charge to zero and check that the displacement goes to zero as well?

**Comment by kyrsjo** [comment] 2017-05-31 15:40
Confirmed! No kick when the charge is zero.

**Comment by rdemaria** [comment] 2017-06-01 18:39
Thanks @kyrsio! @giadarol, I think it would be useful to perform a
realistic test with small coupling with code as it is both to appreciates
the differences  from yours and to see if something unexpected and clear
wrong shows up. Since you already found corner cases that are not correct,
do you think it would be possible write a function that perform a test on
these case and emit in stdout the errors?

**Comment by kyrsjo** [comment] 2017-06-07 17:10
Let's get this merged; we have already fixed one bug, further debugging can proceed in a new branch.

Agreed?

**Comment by kyrsjo** [comment] 2017-06-08 12:49
By the way, do we want the change also for the old style? Currently both are changed (causing the `beam-HO_LR-ibbc` tests to fail).

**Comment by rdemaria** [comment] 2017-06-08 19:29
Yes, also old style was not correct!

**Comment by kyrsjo** [comment] 2017-06-09 08:51
Good. Rerunning the test suite (minus prob1/prob3) now, will bump the version number and merge as soon as that's done assuming no more surprise errors.

Then I think we can make a BOINC release :)

**Comment by rdemaria** [comment] 2017-06-09 09:51
Excellent!

**Closed** 2017-06-09 10:07 UTC
Labels: bug
