### ISSUE TITLE
RF multipole longitudinal kick problem

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#5] opened 2015-08-26 11:50 UTC
## Issue:

RF multipoles (such as crab cavities) work on dpsv = deltaP/P0 = delta, RF cavities work on ejf = total energy
## Why is this a problem:

There is a pile of auxiliary variables for the energy, updating them in different order causes accuracy problems
We may not actually be conserving quantities which should be conserved, by missing a factor beta_0 \approx 1-10{^-9}
## Physics impact:

Long term tracking
Crab emittance growth studies?
## Resources:

https://cds.cern.ch/record/1491234/files/RF-Note_final_1.pdf
http://ab-dep-abp.web.cern.ch/ab-dep-abp/LCU/LCU_meetings/2011/20110419/workoutline.pdf
## Hints from Riccardo:

Pay attention to the definition of sigma - it is not really z!
sigma = s - beta0 c t
Something else in MadX
pz = something unreadable = \sqrt{(1+\delta)^2 + p_x^2 + p_y^2} should be conserved
Normalization of the voltage — a factor beta0 missing?
Hamiltonial / multipole expansion / assumptions in Panofsky-Wenzel theorem
## My notes while reading the code and documentation:

It appears that the hamiltonian is of the form using delta and Delta s
However, the code uses sigmv for Delta s
According to TWIKI, sigmv is sigma = s-beta0_c_t, while Delta s = s - beta c t

**Comment by kyrsjo** [comment] 2016-07-14 07:17
Related issue: In thick6d, the crab may change the energy of the particles. This should trigger an update of the BLOCK matrices; however the call to `subroutine synuthck` (similar to `envarsv) is missing. This is a one-line fix...

**Comment by kyrsjo** [comment] 2016-09-28 13:37
After a quick discussion with Riccardo, it seems this is much easier than what I thought at first. The variable being updated in the longitudinal kick is `dpsv`, i.e. deltaP/P_0. However, the change being applied is actually a change of energy, not relative momentum...

The solution would be to update the energy directly, then use that to update the momentum. This would also solve the problem with numerical noise.

Another thing: The "tilt" part of code looks identical to the non-tilted code. Should there not be some reference to the angle? This code looks pretty pointless to me...

The transverse kick looks OK, using p_z \approx 1+\delta and assuming the physics manual to be correct.

**Comment by rdemaria** [comment] 2017-07-17 12:02
The problem is following:

    crabamp = (ed(ix) /ejfv(j))*c1e3 => V/E
    dpsv(j)=dpsv(j) - crabamp*crabfreq*2pi/clight*xv(xory,j)*cos_rn(sigmv(j)/clight*crabfreq*2pi) 
     => delta_new = delta_old - V/E sin

while it should be
     => E_new = E_old - V sin

In addition unless redefining the voltage to be voltage*beta, also the transverse coordinates are affected by a missing factor.

**Comment by rdemaria** [comment] 2017-07-17 12:23
It also looks like that in the definition of the phase of cavity a factor beta0 is missing since: sigmv = -c beta0 deltaT and not like mads -c Delta t.

**Comment by rdemaria** [comment] 2017-08-16 08:24
The Hamiltonian of a  crab cavity is

H= V/(P0c) sin(w t) x

where

w t = 2pi f sigma/(beta0 c)

with the canonical coordinates

sigma=s-beta0 c t
psigma= (E-E0)/(beta0 P0 c)

therefore

px(new)= px(old) - V/(P0c) sin(2pi f sigma/(beta0 c) )
psigma(new) = psigma(old) - V/(P0c) 2pi f /(beta0 c) cos (2pi f sigma/(beta0 c)) x

the latest can be rewritten with

E(new)=E(old) - V 2pi f/c cos (2pi f sigma/(beta0 c)) x

In Sixtrack we have instead

delta(new)=delta(old) - V/(Pc) 2pi f /c  cos (2pi f sigma/c)) x

which should be replaced by the change in energy instead.

**Comment by rdemaria** [comment] 2018-05-23 07:14
Fixed in #361

**Closed by rdemaria** 2018-05-23 07:14 UTC
Labels: Bug, Tracking
