### ISSUE TITLE
BOINC build broken

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#744] opened 2018-12-12 12:34 UTC
The BOINC build currently isn't working, as it is either segfaulting when opening files, or opening them but failing to write to them.

This thread is for tracking progress on that issue.

According to @JamesMolson , it was working this summer, so it may be related to a recent change in SixTrack.

**Comment by rdemaria** [comment] 2018-12-12 12:58
@JamesMolson can you identify the commit where you last checked?

**Comment by vkbo** [comment] 2018-12-12 14:45
It presumably checkpoints fine with a running BOINC client, which is not the case when we run the test suite, so we can only know when the test exec is out.

The segfault happens only on latest Debian (so far), with the API flag. This was also the case this summer. It runs fine if we use different compilers for the c++ and the fortran code. Both gcc/ifort and gcc/nagfor.

The BOINC version bump that was done in May this year did break a number of things, but only on Windows.

**Comment by vkbo** [comment] 2018-12-12 15:09
> According to @JamesMolson , it was working this summer, so it may be related to a recent change in SixTrack.

Unlikely, as I checked out 4.6.30, and it too segfaulted.

**Comment by vkbo** [comment] 2018-12-12 18:48
Also segfaults on Debian 9 stable with gfortran 6.3.
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7c880d in ???
#1  0x7c7ead in ???
#2  0x77df3f in ???
	at /build/glibc-yWQXbR/glibc-2.24/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#3  0x0 in ???
Segmentation fault
```

**Comment by vkbo** [comment] 2018-12-13 12:54
I suspected, from the error message above, that this is related to static build. Indeed this is the case. Works fine when not building static.

**Comment by vkbo** [comment] 2019-02-02 15:31
I also get segfaults when running the Einstein@Home exec. They have a flag that sends you an executable linking with libc 2.15 instead, which solves the issue. I suspect that this may work for us as well.

My version of Debian has version 2.28, but lxplus7 has 2.17. Execs built on lxplus7 do not segfault.

**Comment by vkbo** [comment] 2019-06-06 09:57
I think we can consider this issue resolved in that sense that the problem is the static linking of glibc. Since we are not supposed to do that, there is no fix other than ... well ... not doing that.

A solution is to build our BOINC releases with ifort or nagfor and link their libc, which does not seem to have this issue.

**Closed by vkbo** 2019-06-06 09:57 UTC
